export type DocumentType = 'RECOMMENDATION_LETTER_MEMBER' 
| 'RECOMMENDATION_LETTER_MINISTER'
|'TRANSFER_LETTER_MEMBER' 
| 'TRANSFER_LETTER_MINISTER ' 
| 'TRANSFER_LETTER_MEMBER,'
| ' DECLARATION_MEMBER_ACTIVE'
| 'DECLARATION_MINISTER_ACTIVE'
| 'MEMBER_APRESENTATION_LETTER' 
| 'MINISTER_APRESENTATION_LETTER'
| 'BAPTISM_CERTIFICATE' 
| 'MEMBER_CERTIFICATE'
| 'MINISTER_CERTIFICATE'
| 'LEADER_CERTIFICATE'
| 'MINISTER_ORDINATION'
| 'COMMUNICATION_OFFICE'
| 'OFFICE'

export interface DocumentRequestDTO {
    
    documentType: DocumentType;

    idMember?: number;
    
    idMinister?: number;

    purpose?: string;

    recipient?: string;
    
    subject?: string;
}